AWSTemplateFormatVersion: 2010-09-09
Description: Create CodePipeline.

Parameters:
  # Source
  GitHubOwner:
    Type: String
    Default: '{{resolve:ssm:github-owner:1}}'
  GitHubToken:
    Type: String
    Default: '{{resolve:ssm:github-token:1}}'
  Repository:
    Type: String
  Branch:
    Type: String
    Default: master
  # Build, Deploy 接頭辞として扱い文字列結合に使う
  ServiceStackName:
    Type: String

Resources:
  # ビルド設定
  CodeBuildProject:
    Description: Creating AWS CodeBuild project
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub Building stage for ${Branch}.
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: AWS_ACCOUNT_ID
            Value: !Sub "${AWS::AccountId}"
          - Name: IMAGE_NAME
            Value: !Join ['', [!Ref ServiceStackName, "-ecr"]]
          - Name: CONTAINER_NAME
            Value: !Join ['-', [!Ref ServiceStackName, "container"]]
        Image: aws/codebuild/docker:18.09.0
        Type: LINUX_CONTAINER
      Name: !Sub ${AWS::StackName}-build
      ServiceRole: !ImportValue CodeBuildRole
      Source:
        Type: CODEPIPELINE
      TimeoutInMinutes: 10

  # ビルド結果保存用のS3Bucketを設定
  ArtifactBucket:
    Type: AWS::S3::Bucket

  # パイプライン設定
  ProjectPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucket
        Type: S3
      Name: !Sub ${AWS::StackName}-pipeline
      RestartExecutionOnUpdate: false
      RoleArn: !ImportValue CodePipelineRoleArn
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref Repository
                Branch: !Ref Branch
                OAuthToken: !Ref GitHubToken
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: SourceOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              OutputArtifacts:
                - Name: CodebuildOutput
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: ECS
              Configuration:
                ClusterName: !ImportValue Vpc1-ECS-Cluster
                ServiceName: !Join ['-', [!Ref ServiceStackName, "service"]]
              InputArtifacts:
                - Name: CodebuildOutput
              RunOrder: 1
