AWSTemplateFormatVersion: 2010-09-09
Description: Create LoadBalancer's TargetGroup and Listener.

Resources:
  # TargetGroup
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !ImportValue Vpc1
      Protocol: HTTP
      Port: 80
      TargetType: ip
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3

  # Listener
  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue Vpc1-LoadBalancer
      Protocol: HTTPS
      Port: 443
      Certificates:
          - CertificateArn: !ImportValue Default-Certificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  LoadBalancerListenerRedirectHttps:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !ImportValue Vpc1-LoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Host: "#{host}"
            Port: 443
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: HTTP_301

Outputs:
  LoadBalancerListener:
    Description: ID of Load Balancer's Listener
    Value: !Ref LoadBalancerListener
    Export:
      Name: Vpc1-LoadBalancerListener
